### ISSUE TITLE
Define and improve demo

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/launch_module_planning#3]
**Context**
As part of our launch module we want students practicing how to demo their work in short, clear presentations. 

The goal of the presentation is to help stakeholders (usually other students and TAs) understand the goals of their launch project and any progress they've made.

**Task** 

- [x] Review existing deck 
- [x] Refine and iterate on deck 
- [x] Rewrite instructions on how to use 
- [ ] Add new instructions to new curriculum format, including deck link
