### ISSUE TITLE
Planning the admin work/estimation of time to deliver the Launch

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/launch_module_planning#4]
**Background**
The Launch module is quite different, with more complex steps than what we had with Final Projects.
We also want to ensure we have volunteers running each bit of it, so we want to have clarity of how long we believe this would take - and then pilot it

**Tasks**
- [ ] Create a simple way of seeing phases in detail and estimation of time
- [ ] Add number of volunteers needed (ratio and/or total)
- [ ] Plan a possible pilot date
