### ISSUE TITLE
Review the current briefing process

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/launch_module_planning#6]
**Background**
We have an incomplete Final Project Proposal form that doesn't give us enough information on this can or cannot be a good briefing for our Launch projects.
Challenge: We need to remember that many organisations don't have anyone technical, so the briefing cannot have purely technical questions. However, we need to understand if it is a full-stack development, for example. 

**Tasks**

- [ ] Read the current [Final Projects Proposal form](https://docs.google.com/forms/d/e/1FAIpQLSf5n0Eigrw2RPOq9jVaVa7rHuMduRYhnwVTDQdKckLnU_rDzg/viewform)
- [ ] Identify must-have information for a new briefing proposal form
- [ ] Create a new form
- [ ] Test it with some organisation and existent briefings
- [ ] Update Curriculum
- [ ] Add it to Launch Canvas
- [ ] Retire the old form
